name: 'build'
on:
  push:
    tags: "build*"
jobs:
  Build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: build
        run: ./gradlew uni-idea-plugin:buildPlugin
      - name: upload plugin to github release page
        uses: avdim/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "uni-idea-plugin/build/distributions/*"
          tags: false
          draft: true
          prerelease: false
          overwrite: true
